version: '3.9'
services:
  frontend:
    container_name: fast_delivery_frontend
    build: ./front-end
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /app-frontend
    volumes:
      - ./front-end:/app-frontend
  backend:
    container_name: fast_delivery_backend
    build: ./back-end
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app-backend
    volumes:
      - ./back-end:/app-backend
    environment:
      - APIPORT=3001
      - MYSQLHOST=db
      - MYSQLPORT=3306
      - MYSQLUSER=root
      - MYSQLPASSWORD=password
  db:
    image: mysql:8.0.21
    container_name: fast_delivery_db
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: 'always'
